name: Backend Destroy
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
    backend-destroy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS Credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: eu-west-2
                role-to-assume: arn:aws:iam::590183931718:role/githubaction

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform destroy
              run: terraform destroy -auto-approve

            